version: "3.9"  # optional since v1.27.0
services:

  keys_ms:
    container_name: firma_keys_ms_test    
    image: ghcr.io/unal-swarch-2022i-1a/firma_keys_ms:prod
    volumes:
      - ./firma_keys_ms/src:/usr/src/app/src
      - ./firma_keys_ms/database:/usr/src/app/database
    extra_hosts:
      - host.docker.internal:host-gateway  

  signing_ms:
    container_name: firma_signing_ms_test
    image: ghcr.io/unal-swarch-2022i-1a/firma_signing_ms:prod
    volumes:
      - ./public:/var/www/html/
      - ./src:/var/www/src/
      - ./tests:/var/www/tests/
    ports:
      - 8092:80      
    extra_hosts:
      - host.docker.internal:host-gateway

  mq:
    container_name: firma_mq_test
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword    
    ports:
      - 15672:15672
      - 5672:5672
