version: "3.9"  # optional since v1.27.0
services:
  user_ms:
    container_name: lab7_user_ms
    build: ./firma_user_ms
    ports:
      - 8090:8090
  ag:
    container_name: lab7_ag   
    build: ./firma_ag
    volumes:
      - ./firma_ag/src:/usr/src/app/src
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway          
  proxy:
    container_name: lab7_proxy
    build: ./firma_proxy
    ports:
      - 80:80    
    extra_hosts:
      - host.docker.internal:host-gateway              