openapi: 3.1.0
info:
  title: Docs microservice
  version: '1.0'
  summary: Microservicio que adminsitra la metadata de los documentos
servers:
  - url: 'http://localhost:8091'
paths:
  '/docs/{docid}':
    parameters:
      - schema:
          type: string
          default: '1'
          example: '1'
        name: docid
        in: path
        required: true
    get:
      summary: Obtener info (metadata) del documento
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doc'
              examples:
                Factura.pdf:
                  value:
                    name: factura.pdf
                    folder: 0
      operationId: get-docs-docid
      parameters:
        - schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjF9.1HpgM-mGLjlZidENBpt3wQ4T7E-JXlvZ44JkHuoLeNk
            default: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjF9.1HpgM-mGLjlZidENBpt3wQ4T7E-JXlvZ44JkHuoLeNk
          in: header
          name: Authorization
          description: Bearer
          required: true
      description: ''
components:
  schemas:
    Doc:
      title: Doc
      type: object
      properties:
        id:
          type:
            - 'null'
            - integer
        name:
          type: string
        folder:
          type:
            - integer
            - 'null'
      examples:
        - name: factura.pdf
          folder: 0
