openapi: 3.1.0
info:
  title: Keys microservice
  version: '1.0'
servers:
  - url: 'http://localhost:8093'
paths:
  '/keys/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: El ID del par de llaves
    post:
      summary: Generar par de llaves del usuario
      operationId: post-keys-id
      responses:
        '201':
          description: Created
    put:
      summary: Regenerar par de llaves del usuario
      operationId: put-keys-id
      responses:
        '202':
          description: Accepted
    delete:
      summary: Eliminar par de llaves del usuario
      operationId: delete-keys-id
      responses:
        '204':
          description: No Content
  '/keys/{id}/public':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Obtener la llave pública del usuario
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                readOnly: true
              examples:
                Public key from user 234:
                  value: '--BEGIN PUBLIC KEY----- MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAZSfzwxio51ITASN7m7Ck5GMA 8gUpSPHKOn6lYQ17ZqGO6YWqjOzYNL/ipxVWq8Ztr1zueOpIFSnKxf7XG1u/FIdk UlufpRcUSahrXxbUJX36+QqkujRvC1XwZTRmhoqiLaO8wHxFMXqJrhgAvr5+Yjtp ftph731rgN77XLAgCQIDAQAB -----END PUBLIC KEY-----'
      operationId: get-keys-id-public
  '/keys/{id}/private':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Obtener la llave privada del usuario
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                private key from user  234:
                  value: '--BEGIN RSA PRIVATE KEY----- MIICWwIBAAKBgQDAZSfzwxio51ITASN7m7Ck5GMA8gUpSPHKOn6lYQ17ZqGO6YWq jOzYNL/ipxVWq8Ztr1zueOpIFSnKxf7XG1u/FIdkUlufpRcUSahrXxbUJX36+Qqk ujRvC1XwZTRmhoqiLaO8wHxFMXqJrhgAvr5+Yjtpftph731rgN77XLAgCQIDAQAB AoGAPNbAD4E+JwsfFQtjIQ9WiI4AEKh3oVqDuyNMMRfDn6YQqJSHxCrUKnpjw1R6 lvGyybSOeoqZ6zlmAc0ijPsFw5XVET1U1PR52RgPTBJJB+pYkGW5LJCtT/lkARE/ NoqqkAgRhWBxl5mSyQWHfjsDtcoebdYpMmQbn0NkKHWzaRECQQDzGpIAZZO093GY D3JaxXdKGnvvRKXn6+cY/FXErtRRVzfIiGUD4fGSP013wdWpgCdHv2ZR5ARv7udo E91PDiwnAkEAypnyD99jVJdwRUh65k/BHseefCQlJEhslr3g7INNAj5/9IdWhs6B I98NEeoCiOQ0PvKAU8Mebu38hj8jEfuATwJAaGIERr9WyOFmmRAo3ejj66GrjXVA d3DHbecLPMSEzdhRT32hQiWGAHHF5aIJCBrKwvfgC1GIxjcijYHaCNPhCQJAGSOp CZcqeCCiabZoqZNT30HdxIGnqizibIH7Gt3f/FtM/Uad0fRlydGviX2D+wB2CymE CuC3MgSNxQqoi16tuQJABfEHYSJ5PAt4BbPZ1jXEbjWtN4bHpcuVQE/Sa0AbzRdP 77nK0sDR02StrgmEozg/Rr3bxfaMYAgaQBvz/zgrtg== -----END RSA PRIVATE KEY-----'
      operationId: get-keys-id-private
components:
  schemas: {}
